preload = /home/connorwallpapers/wallpaper.jpg
splash = false

wallpaper {
    monitor = HDMI-A-1
    path = /home/connorwallpapers/wallpaper.jpg
}

wallpaper {
    monitor = DP-1
    path = /home/connorwallpapers/wallpaper.jpg
}

wallpaper {
    monitor = DP-3
    path = /home/connorwallpapers/wallpaper.jpg
}
