preload = /home/connor/Pictures/Wallpapers/forest.jpg
splash = false

wallpaper {
    monitor = HDMI-A-1
    path = /home/connor/Pictures/Wallpapers/forest.jpg
}

wallpaper {
    monitor = DP-1
    path = /home/connor/Pictures/Wallpapers/forest.jpg
}

wallpaper {
    monitor = DP-3
    path = /home/connor/Pictures/Wallpapers/forest.jpg
}
