preload = /home/connor/wallpapers/wallpaper.jpg
splash = false

wallpaper {
    monitor = eDP-1
    path = /home/connor/wallpapers/wallpaper.jpg
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/connor/wallpapers/wallpaper.jpg
}

wallpaper {
    monitor = DP-1
    path = /home/connor/wallpapers/wallpaper.jpg
}

wallpaper {
    monitor = DP-3
    path = /home/connor/wallpapers/wallpaper.jpg
}
